param(
    [switch]$SkipInstaller,
    [switch]$RequireSignature,
    [string]$UpdateManifestUrl = "",
    [string]$SignPfxPath = $env:JSR_SIGN_PFX,
    [string]$SignPfxPassword = $env:JSR_SIGN_PFX_PASSWORD,
    [string]$SignCertThumbprint = $env:JSR_SIGN_CERT_SHA1
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
Set-Location $ProjectRoot
[xml]$Pom = Get-Content (Join-Path $ProjectRoot "pom.xml")
$Version = [string]$Pom.project.version
if ([string]::IsNullOrWhiteSpace($Version)) { throw "Could not read project version from pom.xml" }
$UpgradeUuid = "6E4383F6-E0BD-4A6D-9C66-2263DB58E39F"

function Require-Command([string]$Name, [string]$Hint) {
    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
        throw "$Name was not found. $Hint"
    }
}

Require-Command "java" "Install a JDK 17+ for building. End users will NOT need Java."
Require-Command "javac" "A JRE alone is not enough to build; install a JDK 17+."
Require-Command "jpackage" "Use a JDK that includes jpackage (JDK 17+ recommended)."
Require-Command "mvn" "Install Apache Maven 3.9+."

$UpdateProperties = Join-Path $ProjectRoot "src\main\resources\update.properties"
$UpdateBackup = $null
if (Test-Path $UpdateProperties) { $UpdateBackup = Get-Content $UpdateProperties -Raw }

try {
    if (-not [string]::IsNullOrWhiteSpace($UpdateManifestUrl)) {
        if (-not $UpdateManifestUrl.StartsWith("https://")) {
            throw "UpdateManifestUrl must use HTTPS for release builds."
        }
        @("# Generated by build-windows.ps1", "manifest.url=$UpdateManifestUrl") |
            Set-Content -Path $UpdateProperties -Encoding UTF8
        Write-Host "Update manifest embedded: $UpdateManifestUrl"
    }

    Write-Host "[1/6] Preparing embedded FFmpeg + FFprobe..."
    & (Join-Path $PSScriptRoot "prepare-ffmpeg.ps1")

    Write-Host "[2/6] Building shaded application JAR..."
    & mvn clean package
    if ($LASTEXITCODE -ne 0) { throw "Maven build failed." }

    $JarName = "java-screen-recorder-$Version-all.jar"
    $JarPath = Join-Path $ProjectRoot ("target\" + $JarName)
    if (-not (Test-Path $JarPath)) { throw "Expected shaded JAR was not created: $JarPath" }

    $InputDir = Join-Path $ProjectRoot "target\jpackage-input"
    $DistDir = Join-Path $ProjectRoot "dist"
    $InstallerDir = Join-Path $ProjectRoot "dist-installer"

    Remove-Item $InputDir -Recurse -Force -ErrorAction SilentlyContinue
    Remove-Item $DistDir -Recurse -Force -ErrorAction SilentlyContinue
    Remove-Item $InstallerDir -Recurse -Force -ErrorAction SilentlyContinue
    New-Item -ItemType Directory -Force -Path $InputDir, $DistDir, $InstallerDir | Out-Null
    Copy-Item $JarPath (Join-Path $InputDir $JarName)

    Write-Host "[3/6] Creating self-contained Windows app image (EXE + bundled Java runtime)..."
    & jpackage `
        --type app-image `
        --dest $DistDir `
        --name "JavaScreenRecorder" `
        --app-version $Version `
        --vendor "Java Screen Recorder" `
        --description "Private local screen, audio and webcam recorder" `
        --icon (Join-Path $ProjectRoot "src\main\resources\icons\app-icon.ico") `
        --input $InputDir `
        --main-jar $JarName `
        --main-class "com.example.screenrecorder.ScreenRecorderApp" `
        --java-options "-Dfile.encoding=UTF-8" `
        --java-options "--enable-native-access=ALL-UNNAMED"
    if ($LASTEXITCODE -ne 0) { throw "jpackage app-image build failed." }

    $PortableExe = Join-Path $DistDir "JavaScreenRecorder\JavaScreenRecorder.exe"
    Write-Host "Portable EXE created: $PortableExe"

    Write-Host "[4/6] Code-signing application launcher..."
    & (Join-Path $PSScriptRoot "sign-windows.ps1") `
        -File $PortableExe `
        -PfxPath $SignPfxPath `
        -PfxPassword $SignPfxPassword `
        -CertThumbprint $SignCertThumbprint `
        -Required:$RequireSignature

    if ($SkipInstaller) {
        Write-Host "[5/6] Installer skipped."
        Write-Host "[6/6] Build complete."
        exit 0
    }

    Write-Host "[5/6] Creating Windows installer + uninstall registration..."
    $HasWix = (Get-Command candle.exe -ErrorAction SilentlyContinue) -or (Get-Command wix.exe -ErrorAction SilentlyContinue)
    if (-not $HasWix) {
        throw "WiX was not found. A release installer requires WiX v3+ or v4/v5 on PATH. Use -SkipInstaller only for portable development builds."
    }

    & jpackage `
        --type exe `
        --dest $InstallerDir `
        --name "JavaScreenRecorder" `
        --app-version $Version `
        --vendor "Java Screen Recorder" `
        --description "Private local screen, audio and webcam recorder" `
        --icon (Join-Path $ProjectRoot "src\main\resources\icons\app-icon.ico") `
        --app-image (Join-Path $DistDir "JavaScreenRecorder") `
        --win-per-user-install `
        --win-dir-chooser `
        --win-shortcut `
        --win-menu `
        --win-menu-group "Java Screen Recorder" `
        --win-upgrade-uuid $UpgradeUuid
    if ($LASTEXITCODE -ne 0) { throw "jpackage installer build failed." }

    $Installer = Get-ChildItem $InstallerDir -Filter "*.exe" -File | Select-Object -First 1
    if (-not $Installer) { throw "jpackage completed but no installer EXE was found in $InstallerDir" }

    Write-Host "[6/6] Code-signing installer..."
    & (Join-Path $PSScriptRoot "sign-windows.ps1") `
        -File $Installer.FullName `
        -PfxPath $SignPfxPath `
        -PfxPassword $SignPfxPassword `
        -CertThumbprint $SignCertThumbprint `
        -Required:$RequireSignature

    Write-Host ""
    Write-Host "Release artifacts:"
    Write-Host "  Portable:  $PortableExe"
    Write-Host "  Installer: $($Installer.FullName)"
    Write-Host "Windows uninstall is registered automatically under Settings > Apps > Installed apps."
}
finally {
    if ($null -ne $UpdateBackup) {
        Set-Content -Path $UpdateProperties -Value $UpdateBackup -Encoding UTF8 -NoNewline
    }
}
